repos:
#####
# Basic file cleanliness
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
#####
# Julia
# Due to lack of first-class Julia support, this needs Julia local install
#  and JuliaFormatter.jl installed in the library
- repo: https://github.com/domluna/JuliaFormatter.jl
  rev: v1.0.56
  hooks:
  - id: julia-formatter
#####
# Secrets
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '.*/Manifest\.toml$'
