name = "Rtwithoutrenewal"
uuid = "5f18122a-2e46-11ef-2c26-2d57cbc8fe48"
authors = ["Samuel Abbott <azw1@cdc.gov>", "Samuel Brand <usi1@cdc.gov>", "Zachary Susswein <utb2@cdc.gov>"]
version = "0.2.0"

[deps]
EpiAware = "b2eeebe4-5992-4301-9193-7ebc9f62c855"
EpiAwarePipeline = "66314692-3678-4cbb-b3ac-6fcb54505317"
