@doc raw"
The `TransformLatentModel` struct represents a latent model that applies a transformation function to the latent variables generated by another latent model.

## Constructors

- `TransformLatentModel(model, transform)`: Constructs a `TransformLatentModel` instance with the specified latent model and transformation function.
- `TransformLatentModel(; model, transform)`: Constructs a `TransformLatentModel` instance with the specified latent model and transformation function using named arguments.

## Example

```julia
using EpiAware, Distributions
trans = TransformLatentModel(Intercept(Normal(2, 0.2)), x -> x .|> exp)
trans_model = generate_latent(trans, 5)
trans_model()
```
"
@kwdef struct TransformLatentModel{M <: AbstractTuringLatentModel, F <: Function} <:
              AbstractTuringLatentModel
    "The latent model to transform."
    model::M
    "The transformation function."
    transform::F
end

"""
    generate_latent(model::TransformLatentModel, n)

Generate latent variables using the specified `TransformLatentModel`.

# Arguments
- `model::TransformLatentModel`: The `TransformLatentModel` to generate latent variables from.
- `n`: The number of latent variables to generate.

# Returns
- The transformed latent variables.

"""
@model function EpiAwareBase.generate_latent(model::TransformLatentModel, n)
    @submodel untransformed = generate_latent(model.model, n)
    latent = model.transform(untransformed)
    return latent
end
